name: Build
on:
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies and build
        run: npm install && npm run build
        working-directory: frontend
